### ISSUE TITLE
Don't use ".map"

### ISSUE THREAD

**Issue by munificent** [lrhn/dep-pkgspec#10]
This is the file extension for source maps, so using it for something unrelated to that will confuse users. Also, it isn't a Dart map literal, so "map" doesn't seem very helpful.

Since this file has its own made up syntax, there isn't any obvious existing extension to use. "packages.ini" is probably the closest fit, but that makes it look like something straight of a Windows 95 3.5" floppy. How about any of:
- **.packagespec** - Similar to ".gemspec" from the Ruby world.
- **packagefile** - Similar to "Gemfile" from the Ruby world.
- **packages.txt** - Matches the "packages" directory name and "txt" is a reasonable description of its syntax.
- **dart.packages** - Unambiguous and it does have some extension.

**Comment by sethladd** [comment]
Agreed. .map is overloaded.

**Comment by sethladd** [comment]
I vote for `.dartpackages`

**Comment by sethladd** [comment]
Consensus is that a visible file is best.

`packages.txt` is my favorite option. Closest to the original recommendation, a file extension that is generic and just opens in a text editor.

**Comment by sethladd** [comment]
If you really want to compromise: `packages.map.text`

**Comment by munificent** [comment]
+1 for `packages.txt`, though, of course, I would still prefer making this a Dart file and calling it `packages.dart`.

**Comment by munificent** [comment]
Friendly ping!

I think we'd like to get this proposal accepted tomorrow if possible, but this issue needs to be resolved first.

**Comment by lrhn** [comment]
If ".map" us unacceptable, I'd say ".cfg".
That seems to be a common extension for ".ini"-like files on Unix systems.
The ".txt" is less telling, but possible.

**Comment by munificent** [comment]
I definitely prefer ".cfg" over ".map" and ".ini". I do worry a bit that it will confuse people who may think has something to do with configuration-specific code, which it doesn't.

**Comment by jmesserly** [comment]
> people who may think has something to do with configuration-specific code

I doubt users would think that. "configuration specific code" is not really a common term (see search results for it). It means something to us, who have read the various Dart DEPs, but that's a small set of people.

**Comment by davenotik** [comment]
It sounds like you want to get away from "pub" in the name, as it's not necessarily pub-specific. Using the word "packages" makes sense, as that's what this file is all about.

"packages.json" would feel right, but I read that you all want to keep it super simple to parse without any sort of library help and thus not JSON. "packages.dart" is odd as the syntax is not Dart-y.

I really don't like "packages.txt" as it just feels like a notepad file and feels like it has no place here. Or "packages.cfg" as it feels like I'm configuring some Apache server or something and feels too heavy for what the file's all about. I also don't like that in conversation you'd call it "config" but then have to specify that it's really "c-f-g".

I vote for "packages.spec". It specifies the packages used by your app. It's simple and easily pronounced. It feels like a natural evolution from "pubspec". Would there be a locked version like "packages.lock"? If so, the same 4-char extension for both feels nice as well.

**Comment by davenotik** [comment]
What about just ".packages"? The advantage there is it floats to the top of directory listings with all the other not-for-editing stuff. Certainly not txt, as txt invites you to edit it, and this should not be. And .cfg implies there's all kinds of Dart stuff you can config there. And as it's auto-generated and specific to the local environment, it doesn't go into Git, yes? If so, all the more reason for the dot-something convention?

**Comment by lrhn** [comment]
Going for ".cfg" since that seems that extension is already being used for properties/ini-like files on Unix systems.

**Comment by davenotik** [comment]
FWIW and probably not much at this point, I still think cfg implies the user is configuring something, which this is not. http://en.wikipedia.org/wiki/Configuration_file

I think it should be a dotfile: http://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory

**Comment by seaneagan** [comment]
@davenotik +1.  The only reason to have a file extension is to improve tooling support such as editor syntax highlighting, but `.cfg` does not give us that.  Given that it's a custom format, I'd vote for no file extension, or you can also think of a dot-file as being a custom file extension without any need to have anything before the `.`.

**Comment by zoechi** [comment]
+1 I also think `.packages` is a good choice. The file is normally not of interest for developers and not intended to be edited by the developer, but more an implementation detail.

**Comment by MikeMitterer** [comment]
.packages would also be my favorite.

**Comment by mezoni** [comment]
.dartspec

``` json
{  
   "packages":{  
      "unittest":"home/somebody/.pub/cache/unittest-0.9.9/lib/",
      "async":"/home/somebody/.pub/cache/async-1.1.0/lib/",
      "quiver":"/home/somebody/.pub/cache/quiver-1.2.1/lib/"
   }
}
```

**Comment by radicaled** [comment]
+1 Anything that's a dot-file.

**Comment by mbolgheather** [comment]
+1 for .packages, spoken well.

**Comment by azenla** [comment]
I have to agree with the dot file. Very very few developers would even need to edit this file anyways. :+1:

**Comment by tosh** [comment]
Without having any answers I just wanted to add some more random thoughts (that are more or less independent of each other):

1) When I see a `.txt` file I assume it is written by a human and I don't expect a system to depend on it (eg safe to move, delete, change, …)

2) A cool thing about files ending in `.txt` usually are treated in a way that more obscure file extensions are not (Mac OS X supports quicklook preview, most operating systems will open it in a text editor)

3) I dislike dotfiles (because they are hidden in file browsers, yet usually important) _but_ when I encounter them my assumption is that they either are generated or that their content should be treated/edited with care (which I guess is the case here).

4) I like mezoni's example because the file name tells me it is a file related to dart (imagine a random operations guy encountering the file) and the content of the file tells me it relates to packages and looks easy to load/dump out of the box using dart and other languages.

5) I like the choice of yaml for pubspec files (whereas it is always a bit troublesome when you work on the boundaries of systems (eg find a php/ruby/coffeescript code base that is configured in its own language) and want to glue something together and then have to learn yet another file format or even have to generate/alter text of another programming language (been there, done that).

6) re ini (which like .csv iirc is not very well defined?): there is also toml (https://github.com/toml-lang/toml, dart implementation: https://github.com/just95/toml.dart)

**Comment by davenotik** [comment]
Seth commented over on G+: https://plus.google.com/u/0/+DavidNotik/posts/i1DpNWSSzkX

**Comment by davenotik** [comment]
@sethladd: "there should be only a single packages.cfg file per project. No need to put it in every directory."

It's a package.cfg in the main directory for every project we may have. It's a new extension thrown in the mix and it shows in the midst of a file list. As you show someone a Dart project, it's yet another file, and extension, to explain. At least pubspec.yaml and pubspec.lock are neatly grouped together – and at least one of these is editable, and the other is clearly associated with the first, with ".lock" implying don't edit. As well, coming from broader JS-land w/ "package.json", "packages.cfg" seems like the obvious equivalent in Dart and we'll explain that this is not true. If the file is never to be added to Git, and a behind the scenes thing, make it a dotfile.﻿

**Comment by lrhn** [comment]
Changed to `.packages` now.

**Comment by davenotik** [comment]
Hooray! #peoplepower :smiley_cat:

**Comment by munificent** [comment]
:metal: :rabbit: :metal:

**Comment by davenotik** [comment]
Figured I'd add a link to the notes about the final decision: https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Meetings/2015-05-13%20DEP%20Committee%20Meeting.md#5-package-spec
