### ISSUE TITLE
Would be great if packages_file would be in its own repository 

### ISSUE THREAD

**Issue by zoechi** [lrhn/dep-pkgspec#15]
so it can be added as a dependency easily until it is published to pub.

``` yaml
  packages_file:
    git: https://github.com/lrhn/dep-pkgspec.git/packages_file
```

is not supported by `pub`

**Comment by lrhn** [comment]
We are already working on adding _something_ to pub, but it will be more elaborate and will likely have a different interface. Keep your eyes on https://github.com/dart-lang/package_config/ (API and name may be subject to change, etc.)

**Comment by zoechi** [comment]
Great, thanks!
