### ISSUE TITLE
Can we prohibit "package:" URI's from appearing in the .packages file?

### ISSUE THREAD

**Issue by stereotype441** [lrhn/dep-pkgspec#18]
I don't really see any user benefit to allowing it, and it leads to two problems:
1. It opens up the possibility of infinite recursion occurring during URI resolution.  For example, if the `.packages` file contains:
   
   ```
   foo=package:foo/bar
   ```
   
   Then an attempt to resolve the URI `package:foo/baz.dart` will resolve to `package:foo/bar/baz.dart`, which will in turn resolve to `package:foo/bar/bar/baz.dart`, and so on ad infinitum.
2. In certain situations the analyzer needs to run the URI resolution algorithm in reverse (i.e. it needs to determine, for a given file path, the possible "package:" URI's, if any, which would resolve to that path).  Allowing "package:" URI's to appear in the `.packages` file would complicate this algorithm significantly, since it would have to explore a tree of possibilities rather than a simple list.

**Comment by stereotype441** [comment]
@pq @lrhn

**Comment by sethladd** [comment]
Sgtm thanks for bringing this up

**Comment by pq** [comment]
SGTM too.

**Comment by iposva-google** [comment]
There are many other possibilities for endless recursion in the Dart system. To be honest I do not think we should necessarily limit this.

**Comment by stereotype441** [comment]
We certainly have a precedent for allowing endless recursion at runtime--this is unavoidable considering that Dart is Turing-complete.  But as far as I'm aware we have tried to make the language possible to analyze without endless recursion (this why we prohibit, for example, loops in the class hierarchy, or mutually recursive typedefs).  So from the point of view of precedent, I would argue that since URI's have to be resolved at analysis time, it makes sense to adopt reasonable restrictions to the URI resolution mechanism to avoid endless recursion.

IMHO, the key question is, is it a reasonable restriction to disallow "package:" URI's from ".packages" files?  I already mentioned the benefits in the bug report (tractability and ease of implementation in the analyzer).  The potential cost would be if we prohibit a genuinely useful use case--my belief is that there is no genuinely useful use case, but I'm open to debate on that.

Another thing to consider is that if we make this restriction now, we can always drop it later and retain full backwards compatibility; if we go the other way it would be a breaking change.

Note: I am not certain of this, but I believe that the code currently published to the pub repo "package_config" does not support recursive resolution.  (It doesn't prohibit it; it simply does a single resolution step and returns, leaving the caller to decide how to respond if the resulting URI is another "package:" URI.)  So I believe that whether we decide to prohibit recursion or not, some coding work will be necessary.

**Comment by lrhn** [comment]
I don't think we need to prohibit it, as long as we emphasize that it just won't work.
You get to resolve a package:-URI once, then you try to load the result. If you can't load a package:-URI directly, then that fails (and if you can, you don't need to do resolving - that's a feature for platforms where you need to translate a package location to a loadable location, if we ever create a platform where package data are first-class locations, it won't need a .packages file).
I'll add some text warning you not to use package-URIs and I'll let the helper package throw if you try to create them through its functions, but the format doesn't need to care what URI is on the right hand side.
