### ISSUE TITLE
Walk parent directories too?

### ISSUE THREAD

**Issue by munificent** [lrhn/dep-pkgspec#3]
Right now, the proposal has:

> If a tool does not get a "--package-spec" command line parameter, it may look for a "pkgspec.properties" file in the current directory and use that as a default.

This is great because it means users running dart from the command line won't have to always explicitly pass that flag. However, in pub packages, the Dart entrypoint file typically _won't_ be in the same directory as the pkgspec.properties file. Packages usually look something like:

```
my_app/
  bin/
    my_app.dart
  test/
    awesome_test.dart
    subdir/
      another_test.dart
```

Right now, to handle this, pub places a "packages" symlink in `bin`, `test`, `test/subdir`, etc. Basically, any place an entrypoint could appear, we jam a "packages" symlink in there that points to the "real" packages directory inside the root of the package (`my_app/packages`).

This proposal would let us get rid of the root "packages" and all of the symlinks it contains (yay!) but it doesn't address these secondary ones. The user would have to do something like:

``` bash
$ cd my_app/test
$ dart --package-spec=../pkgspec.properties awesome_test.dart
```

That's pretty verbose and if the user doesn't know to do that, their app just won't run. :disappointed: 

A simple solution would to have the VM walk up parent directories until it finds the file. We'd only do this for the command line VM, and only when the entrypoint is a local file (and not an HTTP URL). That would let us generate:

```
my_app/
  pkgspec.properties
  bin/
    my_app.dart
  test/
    awesome_test.dart
    subdir/
      another_test.dart
```

And then this just works:

``` bash
$ cd my_app/test
$ dart awesome_test.dart
```

What do you think?

**Comment by lrhn** [comment]
I'm not opposed to it.
The VM people might be, because it can be one more delay before launching, but if the VM doesn't start to look for a package-spec file until it see a package:-uri (or it starts looking in parallel with parsing the program), then it might not be a problem.

**Comment by munificent** [comment]
OK, any feedback on this @iposva-google?

**Comment by lrhn** [comment]
How about another approach:
- The VM requires the pkgspec parameter to use packages.
- The VM isn't run directly by most users, instead a "dart" script in sdk/bin is run, which finds the VM, then tries to find a pkgspec file (traversing upwards is fine), and finally runs the dart program.

That kind of stuff doesn't need to be built into the VM.

**Comment by munificent** [comment]
> - The VM isn't run directly by most users, instead a "dart" script in sdk/bin is run, which finds the VM, then tries to find a pkgspec file (traversing upwards is fine), and finally runs the dart program.

We should definitely talk to the VM folks about this. From what I've heard, they've been opposed to any script coming between the user typing `dart` and the VM running.

**Comment by lrhn** [comment]
On Fri, Mar 20, 2015 at 6:15 PM, Bob Nystrom notifications@github.com
wrote:

> - The VM isn't run directly by most users, instead a "dart" script in
>   sdk/bin is run, which finds the VM, then tries to find a pkgspec file
>   (traversing upwards is fine), and finally runs the dart program.
>   
>   We should definitely talk to the VM folks about this. From what I've
>   heard, they've been opposed to any script coming between the user typing
>   dart and the VM running.

That's a perfectly reasonable thing to want, it just entails that any
useful feature must be built directly into the "dart" executable.

**Comment by munificent** [comment]
Hey, Lasse. What's the status on this issue? We talked about it some in the [DEP meeting this week](https://github.com/dart-lang/dart_enhancement_proposals/blob/master/Meetings/2015-03-25%20DEP%20Committee%20Meeting.md). Our thoughts was that the behavior here doesn't need to end up in the _language spec_, but we do need agreement on it and want the VM, dart2js, and the analyzer to agree on what the behavior is.

We're totally fine with disallowing this on HTTP entrypoints, but this proposal isn't useful if the command-line VM doesn't do this for normal file entrypoints. What do you think?

**Comment by lrhn** [comment]
I personally don't care (since I always call dart with a --package-root parameter anyway, having scripts to handle that for me).

So, how about, when you run `dart scheme:///path/somefile.dart` it does:
- check if `scheme:///path/packages.dart` exists, and if so, use that.
- if `scheme` is `file`:
  - check if `scheme:///path/packages/` exists and is a directory, if so use that as package-root the same way it is currently done.
  - otherwise start walking up the path towards the root until a `file:///pathprefix/packages.dart` file is found.
  - if a file isn't found, fail to resolve package: URIs
- if `scheme` is not `file`
  - assume that `scheme:///path/packages/` exists and use that as package-root

If you happen to be running stuff on a network drive, doing the file path traversal can still slow down start-up. 
The VM is free to do these look-ups concurrently with loading other libraries, delaying loading of package: imports until it knows how to resolve them. It is likely that a file is found quickly, if it exists. 

Other tools should consider using the same strategy, but may also require an explicit `--package-spec=packages.dart` parameter.

**Comment by munificent** [comment]
:+1:

I assume this means calling `dart` without an explicit scheme also defaults `file:`, right?

**Comment by lrhn** [comment]
If you just write `dart somefile.dart` then `somefile.dart` should refer to a local file, so the actual URI should be `file:///$cwd/somefile.dart`.

**Comment by iposva-google** [comment]
Lasse, do you really intend to name the file containing the package specification packages.dart? I find that extremely confusing as the file does not contain any Dart code as it is currently being discussed.

**Comment by lrhn** [comment]
If (and only if) the format ends up being a valid Dart library, e.g., something like:

``` dart
const packages = const { 
  r"pkgname" : r"http://example.com/pkgs" 
}
```

then it should be named `packages.dart`. That has been suggested in the latest DEP meeting, but I'm still not sure it's a good idea.

**Comment by sethladd** [comment]
Why not put a packagespec.spec file next to any entry point? That might mean we get duplicate files inside my application directory, but I'm assuming pub client is writing these files anyway. If that simplifies things, works for me.

**Comment by lrhn** [comment]
Current proposal requires walking parent directories for a file: entry point if there is no "packages.map" file or "packages" directory next to the entry point.

**Comment by munificent** [comment]
> That might mean we get duplicate files inside my application directory, but I'm assuming pub client is writing these files anyway.

We want to get pub out of the business of littering files throughout the user's subdirectories.
