### ISSUE TITLE
What should the filename be?

### ISSUE THREAD

**Issue by munificent** [lrhn/dep-pkgspec#7]
Assuming the result of #1 is a different file format, we'll likely want a different file _name_ too since it isn't a properties file anymore. Opening this issue so we can track that.

**Comment by lrhn** [comment]
The file extension is (only) to make editors recognize the file, so it should follow whatever format is chosen.

&lt;rant>Sigh. Extensions are so DOS! When are we ready to move past those and have proper file metadata?&lt;/rant>

**Comment by seaneagan** [comment]
Since it will be `.gitignore`d, maybe start start with a '.' e.g. `.packages`.

**Comment by munificent** [comment]
> Since it will be .gitignored, maybe start start with a '.' e.g. .packages.

I thought about that, but then I realized lots of `.` files are _not_ gitignored: `.travis`, `.gitignore` itself ironically, etc.

I wouldn't mind a leading `.` but I wouldn't mind not having it either.

**Comment by skybrian** [comment]
It's a list of links to packages. How about pkglinks?

I'm in favor of an appropriate extension; they're useful to editors.

**Comment by munificent** [comment]
> How about pkglinks?

I don't think we use "pkg" as a shorthand for "package" anywhere in the system. "Links" is interesting. I was thinking "path" but then that seems weird if the path happens to be an HTTP URL (which I think the proposal permits).

Maybe just `packages.<ext>`?

**Comment by seaneagan** [comment]
+1 for some version of 'packages'... but if it ends up being json, then 'packages.json' is probably too close to [package.json](https://docs.npmjs.com/files/package.json).

**Comment by seaneagan** [comment]
So maybe namespacing it to dart would be good e.g. `dartpackages.<ext>`

**Comment by zoechi** [comment]
+1 for packages.xxx
I was thinking about a folder where all these files go. pubspec.\* in package root is fine, but it would be nice if additional files would go into a directory like `.dart` for example. I would move `.pub` into it as well.

**Comment by munificent** [comment]
> So maybe namespacing it to dart would be good e.g. `dartpackages.<ext>`

I'd be OK with that.

**Comment by munificent** [comment]
If we end up resolving #1 by using Dart syntax, what do you think of just `packages.dart`? That won't collide with npm's `package.json` and mirrors the existing `packages` directory.

**Comment by lrhn** [comment]
I think `packages.dart` would be fine. It should end in `.dart`, and the name `packages` is sufficiently vague that we can add more to it later without changing the name. 
Alternatively it could be `config.dart`, so as to be completely meaningless.

**Comment by munificent** [comment]
> Alternatively it could be config.dart, so as to be completely meaningless.

I actually think it should not contain "config". I think the config-specific stuff we're working on in parallel will be less fixed than this file. By analogy: switching between debug and release mode is a command-line flag, not something you have to edit in a file somewhere.

**Comment by lrhn** [comment]
Filename ended up as "packages.map" with the current format.
