### ISSUE TITLE
Spec *does* need adjustment

### ISSUE THREAD

**Issue by gbracha** [lrhn/dep-pkgspec#8]
The proposal says the spec doesn't need to change. Would that it were so. In fact, some wording needs to change. People have complained recently that the behavior is underspecified; in fact, I think this shows it is overspecified, and the spec should say even less on this topic.  In any case, we do need to figure out what to say in the spec.

**Comment by lrhn** [comment]
This was addressed in the most recent update where I also request the spec to be less specific. It should probably be even less specific than what I wrote there in case we want to map subdirectories of a package individually.
