### ISSUE TITLE
What happens to Platform.packageRoot?

### ISSUE THREAD

**Issue by rmacnak-google** [lrhn/dep-pkgspec#9]
The proposal should include the corresponding changes to dart:io. Presumably this would be adding Platform.packageSpec.

**Comment by seaneagan** [comment]
Wouldn't it be better to put it somewhere in a non-platform specific library (not dart:io or dart:html)?  Either dart:core, or a new dart:platform library possibly.

**Comment by lrhn** [comment]
Ack, the "package root" doesn't make sense if there is no root. It should still work as written - no --package-root command line parameter was passed, so the value is null.

I don't want to expose the package-map directly. I'd prefer something that could load a package:-URI as a resource to actually giving out a resolved package URI.

**Comment by lrhn** [comment]
No plan to add a packageMap getter.
